name: "Build and push to binary cache"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: foo-dogsquared
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: "guix-binary"
      - name: Build custom packages
        run: nix shell nixpkgs#nix-build-uncached --command nix-build-uncached ./ci.nix
